web: cd frontend && npm install && npm run build && API_URL=/api npm run start
api: cd api && pip install -r requirements.txt && gunicorn --chdir api api_project.wsgi:application --bind 0.0.0.0:$PORT --mount-point=/api
